In [1]:
import numpy as np
import pandas as pd

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv1D, Dropout, MaxPool1D, ReLU, Flatten

from sklearn.preprocessing import StandardScaler

In [2]:
samples_per_class = 5000
no_of_classes = 2

In [3]:
noise_df = pd.read_csv("~/SOP/Gravitational Wave Detection Using Deep Learning/data/Final_Merged_Noise_Reduced_No_Abs.csv", header=None)
noise_X = noise_df.values.astype(float)
# noise_y = np.zeros((samples_per_class , 1)).astype(float)


data_df = pd.read_csv("~/SOP/Gravitational Wave Detection Using Deep Learning/data/Final_BBH_Merged_Noise_Signal_Reduced_No_ABS.csv", header=None)
data_X = data_df.values.astype(float)
# data_y = np.ones((samples_per_class , 1)).astype(float)

In [4]:
X = np.concatenate((noise_X, data_X), axis=0)
# Y = np.concatenate((noise_y, data_y), axis=0)

print(len(noise_df.index))
print(X)
# print(Y)

5000
[[ 1.55952588e-19  9.48930874e-20 -2.03908807e-19 ... -1.42081173e-19
   1.56639750e-19  2.06323581e-19]
 [ 1.68342261e-19 -2.32436731e-20  2.01099010e-19 ...  4.92764727e-20
   6.88449772e-21  7.69596876e-20]
 [-1.77127428e-21 -1.16860154e-19 -2.75680221e-20 ...  9.51481870e-20
   1.40486501e-19  1.42635313e-19]
 ...
 [ 1.24066490e-19  2.02760022e-19  7.02894628e-20 ... -1.74086976e-21
   7.28379795e-20  6.74019667e-20]
 [-2.50812218e-19 -3.65408728e-19 -2.59820380e-19 ... -1.21963367e-19
   4.15912167e-20 -2.15545938e-19]
 [-1.66340990e-19 -2.05033650e-20 -2.51719522e-19 ... -1.02534509e-19
   1.37499247e-19 -3.59096226e-20]]
[[0.]
 [0.]
 [0.]
 ...
 [1.]
 [1.]
 [1.]]


In [5]:
# debugging

# mnist = tf.keras.datasets.mnist
# (x_train, y_train),(x_test, y_test) = mnist.load_data()

# print(y_train)
# y_train = tf.keras.utils.to_categorical(y_train)
# y_test = tf.keras.utils.to_categorical(y_test)

# print(y_train)
# print(X[0])

In [6]:
# Alternate way of creating y for the dataset
 
y = [int(i/samples_per_class) for i in range(samples_per_class*no_of_classes)]
y = tf.keras.utils.to_categorical(y)
print(y)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]


In [7]:
# debugging

# x = [[0,0],[1,1]]
# a = [[0],[1]]
# x = np.hstack((x, a))
# # x
# x, a, _ = np.split(x, [len(x[0])-1, len(x[0])], axis = 1)
# x, a 

In [8]:
# shuffling the data

X = np.hstack((X, y))
np.random.shuffle(X)

X, y, _ = np.split(X, [len(X[0])-no_of_classes, len(X[0])], axis = 1)

print(X)
print(y)

[[-8.05570352e-20 -1.76292189e-19 -2.78905620e-19 ...  4.96658190e-20
  -1.37709316e-19  2.02123267e-20]
 [ 1.67836074e-19  1.01601424e-19 -1.15978384e-20 ...  4.92470310e-20
   4.50740090e-20 -1.09826435e-19]
 [ 3.70501874e-20  3.29739776e-20  4.96176489e-20 ...  1.14183882e-20
  -1.08185780e-19 -1.65597939e-19]
 ...
 [-1.81626457e-20  1.40824971e-20  1.49160302e-19 ... -1.48777901e-19
  -1.08221047e-19  2.71519506e-20]
 [-2.68313188e-19 -9.82505725e-20 -3.11455516e-19 ...  3.27260202e-20
   5.94208046e-20 -1.45863531e-19]
 [-5.73372557e-20 -4.05587457e-20 -1.05371917e-19 ... -1.13198792e-19
   7.55365287e-20 -2.39195113e-20]]
[[0. 1.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [0. 1.]
 [0. 1.]]


In [9]:
scaler = StandardScaler()
X = scaler.fit_transform(X)
print(X)

[[-4.66502223e-01 -1.07359821e+00 -1.74433671e+00 ...  5.02581170e-01
  -1.36933782e+00  2.26637884e-01]
 [ 1.12471825e+00  7.27310905e-01 -1.06618344e-03 ...  4.98396855e-01
   4.52394582e-01 -1.06678426e+00]
 [ 2.86896372e-01  2.82565906e-01  3.98155846e-01 ...  1.20432591e-01
  -1.07508789e+00 -1.62151193e+00]
 ...
 [-6.68001951e-02  1.60138337e-01  1.04733176e+00 ... -1.48016600e+00
  -1.07543938e+00  2.95662405e-01]
 [-1.66927888e+00 -5.67844024e-01 -1.95661364e+00 ...  3.33327448e-01
   5.95383678e-01 -1.42522492e+00]
 [-3.17754987e-01 -1.93968081e-01 -6.12621844e-01 ... -1.12467792e+00
   7.56003017e-01 -2.12316594e-01]]


In [10]:
# debugging

# x = [[0,0],[1,1]]
# y = np.expand_dims(x, axis=-1)
# print(y, y.shape)

In [11]:
X = np.expand_dims(X, axis=-1)

In [29]:
model = Sequential()

model.add(Conv1D(64, 32, input_shape = (16384,1)))
model.add(MaxPool1D(4, 4))
model.add(ReLU())
model.add(Conv1D(128, 64))
model.add(MaxPool1D(4, 4))
model.add(ReLU())
model.add(Conv1D(256, 64))
model.add(MaxPool1D(4, 4))
model.add(ReLU())
model.add(Conv1D(512, 128))
model.add(MaxPool1D(4, 4))
model.add(ReLU())
model.add(Flatten())
model.add(Dense(13824))
model.add(Dense(128, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.2))                         # dropout rate not givem
model.add(Dense(2, activation=tf.nn.softmax))

# learning rate not given
model.compile(optimizer=tf.keras.optimizers.Adam(0.001), loss='categorical_crossentropy', metrics=['accuracy'])

In [30]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_4 (Conv1D)            (None, 16353, 64)         2112      
_________________________________________________________________
max_pooling1d_4 (MaxPooling1 (None, 4088, 64)          0         
_________________________________________________________________
re_lu_4 (ReLU)               (None, 4088, 64)          0         
_________________________________________________________________
conv1d_5 (Conv1D)            (None, 4025, 128)         524416    
_________________________________________________________________
max_pooling1d_5 (MaxPooling1 (None, 1006, 128)         0         
_________________________________________________________________
re_lu_5 (ReLU)               (None, 1006, 128)         0         
_________________________________________________________________
conv1d_6 (Conv1D)            (None, 943, 256)         

In [14]:
# print(X1.shape, y.shape)
# X2 = X1[:1600, :]
# y2 = y[:1600, :]

# X3 = X1[1600:2000, :]
# y3 = y[1600:2000, :]
# print(X2.shape, y2.shape)
print(X3.shape, y3.shape)

(10000, 16384, 1) (10000, 2)
(1600, 16384, 1) (1600, 2)
(400, 16384, 1) (400, 2)


In [26]:
# print(X.shape, y.shape)
# X2 = X[:10, :]
# y2 = y[:10, :]

# X3 = X[10:12, :]
# y3 = y[10:12, :]

# X2 = np.expand_dims(X2, axis=-1)
# X3 = np.expand_dims(X3, axis=-1)
# print(X2.shape, y2.shape)
# print(X3.shape, y3.shape)

(10000, 16384) (10000, 2)
(10, 16384, 1) (10, 2)
(2, 16384, 1) (2, 2)


In [31]:
model.fit(X, y, batch_size=32, epochs=10) #, validation_data=(X3, y3)

Epoch 1/20
3/3 [==============================] - 65s 22s/step - loss: 0.6341 - accuracy: 0.8000
Epoch 2/20
3/3 [==============================] - 3s 1s/step - loss: 10.4500 - accuracy: 0.4000
Epoch 3/20
3/3 [==============================] - 4s 1s/step - loss: 0.5176 - accuracy: 0.6000
Epoch 4/20
3/3 [==============================] - 3s 1s/step - loss: 1.1255 - accuracy: 0.6000
Epoch 5/20
3/3 [==============================] - 3s 1s/step - loss: 0.6633 - accuracy: 0.7000
Epoch 6/20
3/3 [==============================] - 3s 1s/step - loss: 0.6787 - accuracy: 0.7000
Epoch 7/20
3/3 [==============================] - 4s 1s/step - loss: 0.6364 - accuracy: 0.7000
Epoch 8/20
3/3 [==============================] - 4s 1s/step - loss: 0.6168 - accuracy: 0.7000
Epoch 9/20
3/3 [==============================] - 4s 1s/step - loss: 0.6582 - accuracy: 0.7000
Epoch 10/20
3/3 [==============================] - 4s 1s/step - loss: 0.6132 - accuracy: 0.7000
Epoch 11/20
3/3 [=============================