In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from keras.models import load_model

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv1D, Dropout, MaxPool1D, ReLU, Flatten

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [19]:
data_BBH_df = pd.read_csv("/content/gdrive/MyDrive/GW_SOP/Data/BBH_Merged.csv", header=None)
X = data_BBH_df.values.astype(float)

In [4]:
print(len(data_BBH_df.index))
print(X)
print(X.shape)

48
[[ 1.18253696e-19  1.13227778e-19  1.07569806e-19 ...  8.04461658e-19
   7.98344142e-19  7.92290841e-19]
 [ 3.45976600e-20  3.85912813e-20  3.11366157e-20 ... -6.98793280e-20
  -8.41065544e-20 -7.69474724e-20]
 [-4.57705542e-20 -4.01982601e-20 -3.75960757e-20 ... -3.01223743e-19
  -2.91567670e-19 -2.82206414e-19]
 ...
 [ 1.38596654e-19  6.91869816e-20  9.98726882e-20 ...  3.95382795e-19
   3.20616930e-19  3.12722743e-19]
 [-1.98960552e-19 -1.96315297e-19 -1.90878367e-19 ...  1.78857410e-19
   1.76397167e-19  1.73639402e-19]
 [-1.46733543e-19 -1.51102053e-19 -1.67376930e-19 ...  1.31814768e-19
   1.31767538e-19  1.31666911e-19]]
(48, 16384)


In [12]:
# Alternate way of creating y for the dataset
 
y = [1 for i in range(48)]
print(y)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [20]:
# X *= 1e19
# print(X)

X *= 1e18
print(X)

[[ 0.1182537   0.11322778  0.10756981 ...  0.80446166  0.79834414
   0.79229084]
 [ 0.03459766  0.03859128  0.03113662 ... -0.06987933 -0.08410655
  -0.07694747]
 [-0.04577055 -0.04019826 -0.03759608 ... -0.30122374 -0.29156767
  -0.28220641]
 ...
 [ 0.13859665  0.06918698  0.09987269 ...  0.3953828   0.32061693
   0.31272274]
 [-0.19896055 -0.1963153  -0.19087837 ...  0.17885741  0.17639717
   0.1736394 ]
 [-0.14673354 -0.15110205 -0.16737693 ...  0.13181477  0.13176754
   0.13166691]]


In [21]:
X = np.expand_dims(X, axis=-1)
print(X.shape)
print(X)

(48, 16384, 1)
[[[ 0.1182537 ]
  [ 0.11322778]
  [ 0.10756981]
  ...
  [ 0.80446166]
  [ 0.79834414]
  [ 0.79229084]]

 [[ 0.03459766]
  [ 0.03859128]
  [ 0.03113662]
  ...
  [-0.06987933]
  [-0.08410655]
  [-0.07694747]]

 [[-0.04577055]
  [-0.04019826]
  [-0.03759608]
  ...
  [-0.30122374]
  [-0.29156767]
  [-0.28220641]]

 ...

 [[ 0.13859665]
  [ 0.06918698]
  [ 0.09987269]
  ...
  [ 0.3953828 ]
  [ 0.32061693]
  [ 0.31272274]]

 [[-0.19896055]
  [-0.1963153 ]
  [-0.19087837]
  ...
  [ 0.17885741]
  [ 0.17639717]
  [ 0.1736394 ]]

 [[-0.14673354]
  [-0.15110205]
  [-0.16737693]
  ...
  [ 0.13181477]
  [ 0.13176754]
  [ 0.13166691]]]


In [ ]:
model = load_model("/content/gdrive/MyDrive/GW_SOP/Data/bbh_classifier.h5")

In [22]:
pred = model.predict(X)

In [23]:
# print(np.argmax(pred, axis = 1))

In [24]:
y_pred = np.argmax(pred, axis = 1)
correct = 0

for i in range(48):
  if y_pred[i]==y[i]:
    correct += 1

acc = (correct/48)*100
print(f"Total no. of data samples: {len(y)}")
print(f"No. of correct predictions: {correct}")
print(f"accuracy: {acc}")

Total no. of data samples: 48
No. of correct predictions: 8
accuracy: 16.666666666666664
